### ISSUE TITLE
Usar o Git Flow com ou sem o plugin GitFlow?

### ISSUE THREAD

**Issue by tacianosilva** [labens-ufrn/suggestclasses#1]
O fluxo de desenvolvimento utilizando Git, principalmente em equipes médias e grandes, precisa ser bem definido e organizado para evitar problemas de conflitos e versionamento. Existem várias técnicas para controlar o fluxo de desenvolvimento, mas devemos implantá-la com ou sem o uso do [plugin gitflow](https://github.com/nvie/gitflow/wiki/Installation) e do [Git Branching Model](https://nvie.com/files/Git-branching-model.pdf).

Sempre achei o GitFlow com a ferramenta complexo e confuso. Acabei encontrando e lendo o artigo [Git-flow o anti-pattern mais querido da galera](https://medium.com/@paulociecomp/pare-de-usar-o-git-flow-6efc6a287094) do [Paulo Moura](https://medium.com/@paulociecomp). Achei muito pertinente os comentários do Paulo Moura, e concordo com ele.

Pretendo definir um Fluxo de Desenvolvimento baseado no uso mais simples do Git Branching Model.

Gostaria da opinião dos alunos do curso de Sistemas de Informação da UFRN, em especial: @hitallow, @joaoeudes7, @silv4b e @ZASOUROUNIJ. Também gostaria da opinião dos amigos @brunogamacatao, @catharinequintans, @danielfireman, @sormany e @leonardocsantoss.

Links para estudo:

- https://nvie.com/posts/a-successful-git-branching-model/
- https://danielkummer.github.io/git-flow-cheatsheet/index.pt_BR.html
- https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow
- https://medium.com/@lariodiniz/tutorial-git-com-git-flow-476ad906c8ae
- https://www.codewall.co.uk/a-git-flow-explainer-how-to-tutorial/
- https://tableless.com.br/git-flow-introducao/

**Comment by hitallow** [comment]
Sempre utilizo o gitflow, quando trabalho em grupo, ultimamente venho utilizando bem mais que antes, sempre resolve meus problemas principalmente de conflitos, mas realmente é uma confusão na hora de visualizar os commits, porém eu ainda acredito que seja uma alternativa interessante, mas tendo em vista que estamos no âmbito acadêmico, é sempre bom aprender e utilizar ferramentas novas.

**Comment by silv4b** [comment]
Eu também sempre venho tentado usar, individual ou não, apesar de achar bastante verboso, é algo que não me causou tanto desconforto (muito por causa do autocomplete do meu terminal, então é um caso particular), concordo com @hitallow, mas na questão das branches, só ficou mais claro pra mim quando visto de maneira gráfica (com o git kraken por exemplo), creio que poderíamos fazer ou ao menos tentar, ter uma versão nossa de git-flow.

**Comment by ZASOUROUNIJ** [comment]
Ao meu ver o Git-Flow em análise geral realmente é overengineering
principalmente para estudantes pois sua repartição exagerada em commits e
branches trás alguns problemas de leitura e dificulta o aprendizado
principalmente na hora de review do projeto e quando olhado de fora.
Concordo com Taciano sobre usar o modelo mais simples pois em projetos
acadêmicos o interessante é o aprendizado da leitura dos versionamentos e
suas aplicações.

Em seg, 4 de nov de 2019 às 09:39, Bruno Silva <notifications@github.com>
escreveu:

**Comment by danielfireman** [comment]
Venho usando um modelo bem simples nos meus projetos acadêmicos e pessoais. Tem apenas uma branch fixa (a master) e cada feature ou mudança é feita na sua própria branch. Depois da revisão de código via PR e aprovação, a pessoa desenvolvedora faz o merge com a master. Releases são feitos via github UI. O merge hell não acontece pois, geralmente, cada dev está olhando uma arquivo ou parte do código diferente e estão sempre sincronizando com a master.

Consegui um bom resultado integrando isso com Heroku, inclusive disparando continuous releases depois da execução de testes automáticos.

**Comment by joaoeudes7** [comment]
No artigo do Paulo Moura eu vi uma frase bem interessante: "Nenhuma ferramenta ou método vai lhe salvar se você tiver um processo ruim.", e isso leva a duas formas de pensar. 

Eu acho interessante o uso do GitFlow quando se tem tarefas bem planejadas e quando já tem definida como vai estruturar suas versões de release, falo isso quando se utiliza algo como deploy automático ao passar por alterações na Master (onde tudo já está testado e em real versão de produção) e não vejo realizar tal coisa de forma segura (quando se trabalha em grupo) sem o uso de GitFlow.
Basta ver alguns projetos mais famosos por meio de ferramentas como "Git Graph" e Git Kraken (como @silv4b  falou) verificar que não é tão monstruoso assim.

Entretanto, em casos quando você seja o único a trabalhar num projeto eu vejo o GitFlow mais como perca de tempo. (A menos q seja aprendizado como @hitallow falou)

**Comment by tacianosilva** [comment]
> Eu também sempre venho tentado usar, individual ou não, apesar de achar bastante verboso, é algo que não me causou tanto desconforto (muito por causa do autocomplete do meu terminal, então é um caso particular), concordo com @hitallow, mas na questão das branches, só ficou mais claro pra mim quando visto de maneira gráfica (com o git kraken por exemplo), creio que poderíamos fazer ou ao menos tentar, ter uma versão nossa de git-flow.

Obrigado pela opinião de todos. Concordo com você, que o GitFlow é importante. O que achei desnecessário foi a quantidade de branches fixas e o abandono da master. Não sei se o git flow será nativo em uma versão mais simples.

**Comment by tacianosilva** [comment]
> Venho usando um modelo bem simples nos meus projetos acadêmicos e pessoais. Tem apenas uma branch fixa (a master) e cada feature ou mudança é feita na sua própria branch. Depois da revisão de código via PR e aprovação, a pessoa desenvolvedora faz o merge com a master. Releases são feitos via github UI. O merge hell não acontece pois, geralmente, cada dev está olhando uma arquivo ou parte do código diferente e estão sempre sincronizando com a master.
> 
> Consegui um bom resultado integrando isso com Heroku, inclusive disparando continuous releases depois da execução de testes automáticos.

@danielfireman o modelo simplificado que você usa está escrito em algum lugar?

**Comment by danielfireman** [comment]
@tacianosilva não exatamente, mas eu tento seguir os princípios de [integração contínua](https://www.thoughtworks.com/continuous-integration) e trago isso para o dia a dia. Os repositórios ao redor de [dadosjusbr](https://github.com/dadosjusbr) vem usando esse modelo. Inclusive fazendo deployment contínuo do [site](https://github.com/dadosjusbr/remuneracoes)
