### ISSUE TITLE
:bug: Bug em test_sugestao.py 

### ISSUE THREAD

**Issue by wanessabezerra** [labens-ufrn/suggestclasses#260]
Falha encontrada após rodar 
```shell
coverage run -m unittest discover
```

FAIL: test_choques_solicitacao (core.tests.test_sugestao.SugestaoTests)
Teste para a choques na inclusão de Solicitação de Turma por um discente.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wanessa/suggestclasses/core/tests/test_sugestao.py", line 159, in test_choques_solicitacao
    self.assertIsNotNone(choque_comp)
AssertionError: unexpectedly None

**Comment by tacianosilva** [comment]
A verificação de choques, na versão atual, não verifica solicitações de turmas do mesmo componente, mas em horários diferentes. Ou seja, não há choque de horários.
